DROP TABLE IF EXISTS categories CASCADE;
DROP TABLE IF EXISTS events CASCADE;
DROP TABLE IF EXISTS compilation CASCADE;

CREATE TABLE IF NOT EXISTS categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(250) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(120) NOT NULL,
    annotation VARCHAR(2000) NOT NULL,
    description VARCHAR(7000) NOT NULL,
    event_date timestamp WITHOUT TIME ZONE NOT NULL,
    created_on timestamp WITHOUT TIME ZONE NOT NULL,
    published_on timestamp WITHOUT TIME ZONE,
    initiator_id BIGINT NOT NULL,
    category_id BIGINT NOT NULL REFERENCES categories(id),
    state VARCHAR(22) NOT NULL,
    lat FLOAT,
    lon FLOAT,
    paid BOOLEAN NOT NULL,
    participant_limit INT NOT NULL,
    request_moderation BOOLEAN NOT NULL,
    confirmed_requests INT NOT NULL,
    views BIGINT NOT NULL
);

CREATE TABLE IF NOT EXISTS compilation (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pinned BOOLEAN NOT NULL DEFAULT FALSE,
    title VARCHAR(128) NOT NULL UNIQUE
);

CREATE TABLE  IF NOT EXISTS compilation_events (
    compilation_id BIGINT NOT NULL,
    event_id BIGINT NOT NULL,
    PRIMARY KEY (compilation_id, event_id),
    CONSTRAINT fk_ce_to_compilation FOREIGN KEY(compilation_id) REFERENCES compilation(id),
    CONSTRAINT fk_ce_to_event FOREIGN KEY(event_id) REFERENCES events(id)
);